IF DB_ID(N'MyNotes') IS NULL CREATE DATABASE [MyNotes];
GO
USE [MyNotes];
GO
IF OBJECT_ID(N'dbo.Users', N'U') IS NULL
CREATE TABLE dbo.Users(
  Id INT IDENTITY PRIMARY KEY,
  Email NVARCHAR(255) NOT NULL UNIQUE,
  PasswordHash NVARCHAR(255) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);
IF OBJECT_ID(N'dbo.Notes', N'U') IS NULL
BEGIN
  CREATE TABLE dbo.Notes(
    Id INT IDENTITY PRIMARY KEY,
    UserId INT NOT NULL REFERENCES dbo.Users(Id) ON DELETE CASCADE,
    Title NVARCHAR(200) NOT NULL,
    Content NVARCHAR(MAX) NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    UpdatedAt DATETIME2 NULL
  );
  CREATE INDEX IX_Notes_UserId_CreatedAt ON dbo.Notes(UserId, CreatedAt DESC);
END
IF OBJECT_ID(N'dbo.Notes_SetUpdatedAt', N'TR') IS NOT NULL DROP TRIGGER dbo.Notes_SetUpdatedAt;
GO
CREATE TRIGGER dbo.Notes_SetUpdatedAt ON dbo.Notes AFTER UPDATE AS
BEGIN
  SET NOCOUNT ON;
  UPDATE n SET UpdatedAt = SYSUTCDATETIME()
  FROM dbo.Notes n INNER JOIN inserted i ON n.Id = i.Id;
END
GO
